[package]
name = "moinai"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = { workspace = true }
common = { workspace = true }
ehttp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
egui_extras = { workspace = true }
eframe = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
poll-promise =  { version = "0.3.0", features = [] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
poll-promise =  { version = "0.3.0", features = ["web"] }