[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = { workspace = true }
eframe = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }