[package]
name = "tool"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = { workspace = true }
common = { workspace = true }
uuid = { workspace = true }
urlencoding = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }