[package]
name = "sketch3"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = { workspace = true }
common = { workspace = true }
three-d = { workspace = true }
three-d-asset = { workspace = true }
csv = { workspace = true }
serde = { workspace = true }
serde_repr =  { workspace = true }
serde_json = { workspace = true }
zip = { workspace = true }
weldr = { workspace = true }
glam = { workspace = true }
rfd = { workspace = true }
bytemuck = { workspace = true }
obj-exporter = "0.2.0"
stl_io = "0.8.5"
gltf = "1.4.1"
ehttp = { workspace = true }
draco-gltf-rs = { git = "https://github.com/Niki123456123456/draco-gltf-rs.git" }
# draco-gltf-rs = {path = "/Users/nnord/uni/projects/draco-gltf-rs"}
reqwest = "0.11"
geoconv = "0.7.1"
fusion-ahrs = "0.2.0"
nalgebra = "0.34"

wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
web-sys = { version = "0.3.70", features = [
  'Window',
  'DeviceMotionEvent',
  'DeviceOrientationEvent',
  'DeviceAcceleration',
  'DeviceRotationRate',
  'console',
  'Performance',
  'PerformanceTiming',
  'HtmlAnchorElement',
  "Response",
  "Request",
  "RequestInit",
  "Headers",
  "Crypto",
  "Navigator",
] }
js-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
poll-promise =  { version = "0.3.0", features = [] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
poll-promise =  { version = "0.3.0", features = ["web"] }
